services:
  jekyll:
    volumes:
        - './:/srv/jekyll'
    ports:
        - '4000:4000'
        - '35729:35729'
    image: jekyll/jekyll:3.8
    command: jekyll serve --incremental --livereload --force_polling --destination /tmp/_site --config _config-dev.yml
